# Generated by Django 4.2.16 on 2024-11-05 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Otp code')),
                ('type', models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset password')], max_length=60, verbose_name='Verification type')),
                ('expires_in', models.DateTimeField(verbose_name='Expires in')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Otp',
                'verbose_name_plural': 'Verification Otps',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('apartment', models.CharField(max_length=120, verbose_name='Apartment')),
                ('street', models.TextField(verbose_name='Street')),
                ('pin_code', models.CharField(max_length=120, verbose_name='Pin code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
    ]
